language: node_js
node_js:
- 10.6.0
install:
- npm install -g firebase-tools
script:
- 
deploy:
  provider: firebase
  token:
    secure: "AQgfu+XHn56IS3IGm1M8ZKadQq0xjKoFseigk96nXwu8U5QP6e0TFBV08zA5tC3TioB2kcs52w5O74O4kC9JO77+R0wFXLWzvrJdfP44iGW9aRdxqPcIgw7S8zsrXRtW+T1DtNXJGQqJbxZn+pAbbFNeFL/h3WMjgr27Xdr7EyrHKHXA8nrvRWQIAlKsG0ZivMJNcDJlI2fr7OkZS3BDBdRgBddTT0vguIl7c7xJZdXg48ML/sp8fjrbtlcszHp0k9EdUXMwBQaqk9ddGK2kc8emKj4lIE/hSmu0kpYHZfdZQp7AIk8Z7MuHT/PvASB0hMQsAsKaKmLdjxmw0jHSlLX+EqmckTAtmuzcabTO3wYx4m/b5kWyqGIZXB+wFIhDVfnFq14JR6T0Ccm6XK20ZTp67PVDUElwZAXiE+vtQgH4MW5WI2a7j2Lr3UqTq4YkS5WvcRNqOI2WfI9UUEpdBxTeSqT01AU49qGSDPwcclZ2omzbWl9vfuqWTNWga1F9Ruxd2J5ehTPRGaq8cwZumza/MZpyoyKGujg4jg5xDxnUuK+4FRPomJ330+0GbtSsmrzNHgwjFmF85S4m7IYUT2EPLeEg+QJpoO86N0AFpuls/jjBBr9YhB85TvJ0uzsLrbRsDVKyYKWDzC3pOcuo7LziMXjFbu3SG4HIckzVRFU="
