language: node_js
node_js:
- 10.6.0
install:
- npm install -g firebase-tools
script:
- 
deploy:
  provider: firebase
  token:
    secure: "R7sodiTK2907y054yF3ab0yq0UTaZ36FsyG/K5zLoDlhMp6954ReVvDC5xIGTsfPpAB9AclrK6iYr5vmWAKpTZ19suJMT4Nyg0q3FJe/rmAGLJ/gJDLYFbjxH2G3zoW/YUL2FKhY1FSD9balahxkWDEZ/8JKXh/icgungDClJXuXptJ8+j5PkDZSr+cP/Rw9qBdzdGQPL8mFKcPES9DoFItITog3QCxp1jyR14VfRl5Cs2Aw+tysYlS2rMa3plgeBE+aEU6yeLjtbxpY2iFoh9GYuMrKj3OfcxZLY9dGqGk68e4Att2M92RkmxqQAZYyW4Wqhs4/DeLsoTzY6zxqF6KZWpS2RXmdRTkG+ofHl6HYp6hSnnQgTL8M+Eqzaz6Nx9RFSOaA97gqkkuyfADt0DOGYlrO8hwiE/LAyH5aK7imzic3ZqWKNHX4DQKMf6ryT3yTWqyI2nDoavlDmAMeeQO9HbMcQLp84s0U3iV42d2o4tvja0BOOG3azwsluH/abIu96VFKecCl1JCK5JB0b+E2NHxVyMwS5q7bjnJfFT6QvpF8AtrJkJLG9wDTSC5BefhW8tl7qMyZahQxjYGUkMvjoBINIb5CNV6/akc5UMvtuOE14Fhkwu/+muewhmHosJe7Sjs5uLC8sF3nMnxe+QbYk5q+q4CHD/gauxzvRH4="
