language: node_js
node_js:
  - 10.6.0
before_script:
  - export PATH=./functions/node_modules/.bin:$PATH
install:
  - npm install -g firebase-tools
  - npm --prefix ./functions/ install
  - ls la functions/node_modules/.bin
script:
  - echo "deploying"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
cache:
  directories:
    - "node_modules"
