language: node_js
node_js:
  - 8.12.0
install:
  - npm install -g firebase-tools
  - npm --prefix ./functions/ install
script:
  - echo "deploying"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
cache:
  directories:
    - "node_modules"
