language: node_js
node_js:
  - 10.6.0
install:
  - npm install -g firebase-tools
  - npm install
script:
  - echo "deploying"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
cache:
  directories:
    - "node_modules"
